on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Docker
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      # Step 3: Run InfluxDB container
      - name: Run InfluxDB Container
        run: |
          docker run -d -p 8086:8086 --name=influxdb influxdb

      # Step 4: Install Ngrok
      - name: Install Ngrok
        run: |
          sudo apt-get install unzip
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install ngrok

      # Step 5: Install jq to parse JSON
      - name: Install jq
        run: sudo apt-get install jq

      # Step 6: Authenticate Ngrok
      - name: Authenticate Ngrok
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      # Step 7: Run Ngrok to expose InfluxDB port 8086
      - name: Expose InfluxDB using Ngrok
        run: |
          nohup ngrok http 8086 &
          sleep 5  # Initial wait time for Ngrok to initialize

      # Step 8: Wait for Ngrok to provide a public URL
      - name: Wait for Ngrok public URL
        run: |
          TIMEOUT=30  # Maximum wait time in seconds
          ELAPSED=0
          INTERVAL=2  # Interval to wait before checking again
          while [ $ELAPSED -lt $TIMEOUT ]; do
            NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url")
            if [ "$NGROK_URL" != "null" ]; then
              echo "Your public InfluxDB URL is: $NGROK_URL"
              break
            fi
            echo "Waiting for Ngrok to provide a public URL..."
            sleep $INTERVAL
            ELAPSED=$((ELAPSED + INTERVAL))
          done

          if [ "$NGROK_URL" == "null" ]; then
            echo "Ngrok did not provide a public URL within $TIMEOUT seconds."
            exit 1
          fi
