runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker environment
      - name: Set up Docker
        run: sudo apt-get install docker.io

      # Step 3: Run InfluxDB container
      - name: Run InfluxDB Container
        run: |
          docker run -d -p 8086:8086 --name=influxdb influxdb

      # Step 4: Install Ngrok
      - name: Install Ngrok
        run: |
          sudo apt-get install unzip
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install ngrok

      # Step 5: Install jq to parse JSON
      - name: Install jq
        run: sudo apt-get install jq

      # Step 6: Run Ngrok to expose InfluxDB port 8086
      - name: Expose InfluxDB using Ngrok
        run: |
          nohup ngrok http 8086 &
          sleep 5

      # Step 7: Fetch Ngrok public URL
      - name: Fetch Ngrok public URL
        run: |
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r ".tunnels[0].public_url")
          echo "Your public InfluxDB URL is: $NGROK_URL"
