on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Docker
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      # Step 3: Run InfluxDB container
      - name: Run InfluxDB Container
        run: |
          docker run -d -p 8086:8086 --name=influxdb influxdb

      # Step 4: Install Localtunnel
      - name: Install Localtunnel
        run: |
          npm install -g localtunnel

      # Step 5: Expose InfluxDB using Localtunnel
      - name: Expose InfluxDB with Localtunnel
        run: |
          lt --port 8086 --subdomain your-subdomain-name --local-host 127.0.0.1 > lt.log &
          sleep 5  # Wait for Localtunnel to establish the connection

      # Step 6: Fetch Localtunnel public URL
      - name: Fetch Localtunnel URL
        run: |
          LT_URL=$(grep -o 'https://[a-z]*.loca.lt' lt.log | head -1)
          echo "Your public InfluxDB URL is: $LT_URL"
          
      # Optional: Sleep for a specific time to keep the job running
      - name: Keep job running
        run: |
          sleep 21600  # Adjust the sleep time as needed (6 hours here)
